server {
    listen 192.168.0.153:80;
    server_name nostrakzn.ru www.nostrakzn.ru 195.19.144.143;

    root /var/www/nostra/current;
    index index.html;

    client_max_body_size 12m;

    location = /api/request {
        limit_except POST { deny all; }
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/nostra/current/api/request.php;
        fastcgi_param SCRIPT_NAME /api/request.php;
        fastcgi_pass unix:/var/www/php-fpm/1.sock;
        fastcgi_read_timeout 30s;
    }

    location /_next/static/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ \.php$ {
        return 404;
    }
}
